# Generated by Django 4.0 on 2022-01-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(db_index=True, max_length=150, verbose_name='نام خانوادگی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیرکل')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمند')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id', 'created_date'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('fk_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parent', to='main.category', verbose_name='سر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='آدرس عکس')),
            ],
            options={
                'verbose_name': 'آیکون',
                'verbose_name_plural': 'آیکون ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('weight', models.FloatField(verbose_name='وزن')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='media/images/product/', verbose_name='عکس')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='main.category', verbose_name='دسته بندی')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_icon', to='main.icon', verbose_name='آیکون')),
                ('tags', models.ManyToManyField(blank=True, related_name='product_tags', to='main.Tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='main.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش',
                'verbose_name_plural': 'جزئیات سفارشات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('zipcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('total_price', models.BigIntegerField(verbose_name='هزینه کل')),
                ('payment_type', models.CharField(choices=[('in-place', 'پرداخت در محل'), ('online', 'پرداخت آنلاین')], max_length=8, verbose_name='نوع پرداخت')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('items', models.ManyToManyField(blank=True, related_name='order_details', to='main.OrderDetails', verbose_name='جزئیات سفارش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to='main.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('id',),
            },
        ),
    ]
