# Generated by Django 4.0 on 2022-01-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id', 'create_date'), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
