# Generated by Django 4.0 on 2022-01-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fk_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parent', to='main.category', verbose_name='سر دسته'),
        ),
    ]
