# Generated by Django 4.0 on 2022-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_status_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0, verbose_name='هزینه کل'),
        ),
    ]
