# Generated by Django 4.0 on 2022-01-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_fk_parent'),
        ('main', '0004_alter_order_total_price'),
    ]

    operations = [
    ]
